[tools]
pipx = "latest"
"github:nvim-neorocks/lux" = "latest"

# lsp servers linters and tools
yamllint = "latest"
yamlfmt = "latest"
lua-language-server = "latest"
stylua = "latest"
marksman = "latest"
taplo = "latest"
tinymist = "latest"
"npm:parinfer" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:quantonganh/snippets-ls" = "latest"
"npm:@neo4j-cypher/language-server" = "latest"
"npm:@ember-tooling/ember-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:markdown-preview" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:eslint-lsp" = "latest"
"npm:prettier" = "latest"
"npm:jsonlint" = "latest"
"npm:djlint" = "latest"
"npm:htmllint" = "latest"
"pipx:pylint" = "latest"
"npm:tree-sitter-cli" = "latest"
"github:clangd/clangd" = "latest"
"github:clojure-lsp/clojure-lsp" = "latest"
"github:nim-lang/nimble" = "0.20.1"
[tools."github:redhat-developer/vscode-xml"]
version = "latest"
rename_exe = "lemminx"
